from .user import User
from .teacher import Teacher
from .student import Student
from .faculty import Faculty
from .staff import Staff
from .subject import Subject
from .subject_group import SubjectGroup
from .grades import Grades
from .career import Career
from .dependency import Dependency