# Generated by Django 5.1.2 on 2024-10-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('personal_email', models.EmailField(max_length=200, unique=True)),
                ('institutional_email', models.EmailField(max_length=200, unique=True)),
                ('personal_email_password', models.CharField(max_length=200)),
                ('birthday', models.DateField()),
                ('recovery_token', models.CharField(max_length=200, null=True, unique=True)),
            ],
        ),
    ]
