# Generated by Django 5.1.2 on 2024-10-30 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisistApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='divisistApp.user')),
                ('position', models.CharField(choices=[('DECANO', 'Decano')], max_length=10)),
            ],
            bases=('divisistApp.user',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='divisistApp.user')),
                ('consecutive', models.CharField(max_length=6, unique=True)),
            ],
            bases=('divisistApp.user',),
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('dean', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='divisistApp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('active_pensum', models.CharField(max_length=2, null=True)),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='divisistApp.faculty')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='divisistApp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='divisistApp.user')),
                ('consecutive', models.CharField(max_length=4, null=True)),
                ('state', models.CharField(choices=[('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20)),
                ('career', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='divisistApp.career')),
            ],
            bases=('divisistApp.user',),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutive', models.CharField(max_length=4)),
                ('semester', models.SmallIntegerField()),
                ('name', models.CharField(max_length=128)),
                ('credits', models.SmallIntegerField()),
                ('hours', models.SmallIntegerField()),
                ('pensum', models.CharField(max_length=2)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='divisistApp.career')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=1)),
                ('academic_year', models.CharField(max_length=7)),
                ('max_capacity', models.SmallIntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='divisistApp.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='divisistApp.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_exam', models.DecimalField(decimal_places=1, max_digits=1, null=True)),
                ('second_exam', models.DecimalField(decimal_places=1, max_digits=1, null=True)),
                ('third_exam', models.DecimalField(decimal_places=1, max_digits=1, null=True)),
                ('final_exam', models.DecimalField(decimal_places=1, max_digits=1, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisistApp.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisistApp.subjectgroup')),
            ],
        ),
    ]
