# Generated by Django 5.1.2 on 2024-10-30 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divisistApp', '0002_staff_teacher_faculty_career_student_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='institutional_email_password',
        ),
    ]
