# Generated by Django 5.1.2 on 2024-10-28 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisistApp', '0002_rename_personal_email_password_user_institutional_email_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='divisistApp.user')),
                ('position', models.CharField(choices=[('dean', 'Dean')], max_length=10)),
            ],
            bases=('divisistApp.user',),
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('dean', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='divisistApp.staff')),
            ],
        ),
    ]
