# Generated by Django 5.1.2 on 2024-10-29 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisistApp', '0004_career_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='divisistApp.career')),
                ('semester', models.IntegerField()),
                ('consecutive', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('credits', models.IntegerField()),
                ('hours', models.IntegerField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('career', 'semester', 'consecutive'), name='unique_subject_code')],
            },
        ),
        migrations.CreateModel(
            name='SubjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=1)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='divisistApp.subject')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('subject', 'group'), name='unique_subject_group_code')],
            },
        ),
    ]
