# Generated by Django 5.1.2 on 2024-10-31 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisistApp', '0005_dependency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependency',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='divisistApp.staff'),
        ),
    ]
