# Generated by Django 5.1.2 on 2024-11-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisistApp', '0006_alter_dependency_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='required_for', to='divisistApp.subject'),
        ),
    ]
