# Generated by Django 5.1.2 on 2024-11-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisistApp', '0008_user_address_user_cellphone_user_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inclusion_date',
            field=models.DateField(default='2024-06-06'),
        ),
    ]
